import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from '@/components/providers/AuthProvider';
const inter = Inter({ subsets: ['latin'] });
import '@/public/styles/globals.scss';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
//<AuthProvider>next auth 관련 삭제

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="__next">{children}</div>
      </body>
    </html>
  );
}
