import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/public/styles/globals.scss';
import '@/public/styles/styles.scss';
import ClientWrapper from '@/components/ClientWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <ClientWrapper>
          <div className="content_box">{children}</div>
        </ClientWrapper>
      </body>
    </html>
  );
}
